apiVersion: apps/v1
kind: Deployment

metadata:
  name: cartservice

  labels:
    app: cartservice
    component: backend
    service: cartservice

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: cartservice

  template:
    metadata:
      labels:
        app: cartservice
        component: backend
        service: cartservice

    spec:
      containers:
        - name: cartservice

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

              name: grpc

              protocol: TCP

          env:
            {{- range .Values.containerEnvVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
