apiVersion: apps/v1
kind: Deployment

metadata:
  name: shippingservice

  labels:
    app: shippingservice
    component: backend
    service: shippingservice

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: shippingservice

  template:
    metadata:
      labels:
        app: shippingservice
        component: backend
        service: shippingservice

    spec:
      containers:
        - name: shippingservice

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: grpc
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          env:
            {{- range .Values.containerEnvVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
