helm:
  parameters:
  - name: image.repository
    value: 333982363119.dkr.ecr.us-west-2.amazonaws.com/boutique-frontend
    forcestring: true
  - name: image.tag
    value: 7f680c8e
    forcestring: true
