apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet

metadata:
  name: google-boutique
  namespace: argocd

spec:
  generators:
  - git:
      repoURL: https://github.com/Prashant0110/google-boutique-gitops.git
      revision: main
      directories:
      - path: helm/apps/*

  template:
    metadata:
      name: "{{path.basename}}"

      labels:
        app.kubernetes.io/part-of: google-boutique
        image-updater: "true"

    spec:
      project: default

      source:
        repoURL: https://github.com/Prashant0110/google-boutique-gitops.git
        targetRevision: main
        path: "{{path}}"

      destination:
        server: https://kubernetes.default.svc
        namespace: ecommerce-prod

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
        - CreateNamespace=true
