apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: otel-collector
  namespace: argocd

spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: 0.166.0

      helm:
        valueFiles:
          - $values/platform/otel-collector/values.yaml

    - repoURL: https://github.com/Prashant0110/google-boutique-gitops.git
      targetRevision: HEAD
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
