deploymentMode: SingleBinary

singleBinary:
  replicas: 1

backend:
  replicas: 0

read:
  replicas: 0

write:
  replicas: 0

loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem

  schemaConfig:
    configs:
    - from: "2024-01-01"
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

  limits_config:
    retention_period: 168h

gateway:
  enabled: false

monitoring:
  selfMonitoring:
    enabled: false

ruler:
  enabled: true
  alertmanager_url: http://monitoring-kube-prometheus-alertmanager.monitoring.svc.cluster.local:9093
  enable_api: true
  storage:
    type: filesystem
