apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater

metadata:
  name: google-boutique
  namespace: argocd

spec:
  # Global image update behavior
  commonUpdateSettings:
    updateStrategy: newest-build
    ignoreTags:
    - latest

  # GitOps write-back
  writeBackConfig:
    method: git
    gitConfig:
      branch: main
      writeBackTarget: helmvalues

  # Applications managed by this ImageUpdater
  applicationRefs:
  - namePattern: "frontend"

    labelSelectors:
      matchLabels:
        image-updater: "true"

    # Image configuration
    images:
    - alias: frontend
      imageName: 333982363119.dkr.ecr.us-west-2.amazonaws.com/boutique-frontend

      # Tell Image Updater which Helm values to modify
      manifestTargets:
        helm:
          name: image.repository
          tag: image.tag
