apiVersion: apps/v1
kind: Deployment

metadata:
  name: paymentservice

  labels:
    app: paymentservice
    component: backend
    service: paymentservice

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: paymentservice

  template:
    metadata:
      labels:
        app: paymentservice
        component: backend
        service: paymentservice

    spec:
      containers:
        - name: paymentservice

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: grpc
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          env:
            {{- range .Values.containerEnvVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
