apiVersion: v1
kind: Secret

metadata:
  name: github-google-boutique
  namespace: argocd

  labels:
    argocd.argoproj.io/secret-type: repository

type: Opaque

stringData:
  type: git

  url: https://github.com/Prashant0110/google-boutique-gitops.git

  username: Prashant0110

  password: ""
