apiVersion: apps/v1
kind: Deployment

metadata:
  name: productcatalogservice

  labels:
    app: productcatalogservice
    component: backend
    service: productcatalogservice

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: productcatalogservice

  template:
    metadata:
      labels:
        app: productcatalogservice
        component: backend
        service: productcatalogservice

    spec:
      containers:
        - name: productcatalogservice

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

              name: grpc

              protocol: TCP
