apiVersion: apps/v1
kind: Deployment

metadata:
  name: checkoutservice

  labels:
    app: checkoutservice
    component: backend
    service: checkoutservice

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: checkoutservice

  template:
    metadata:
      labels:
        app: checkoutservice
        component: backend
        service: checkoutservice

    spec:
      containers:
        - name: checkoutservice

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: grpc
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          env:
            {{- range .Values.containerEnvVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
