replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice
  tag: v0.10.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 50051
  targetPort: 50051

containerEnvVars:
  - name: PORT
    value: "50051"

  - name: DISABLE_PROFILER
    value: "1"
