apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "emailservice.fullname" . }}

  labels:
    app: {{ include "emailservice.name" . }}
    component: backend
    service: emailservice

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "emailservice.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "emailservice.name" . }}
        component: backend
        service: emailservice

    spec:
      containers:
        - name: emailservice

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

              name: grpc

              protocol: TCP
