apiVersion: apps/v1
kind: Deployment

metadata:
  name: currencyservice

  labels:
    app: currencyservice
    component: backend
    service: currencyservice

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: currencyservice

  template:
    metadata:
      labels:
        app: currencyservice
        component: backend
        service: currencyservice

    spec:
      containers:
        - name: currencyservice

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: grpc
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          env:
            {{- range .Values.containerEnvVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
