mode: deployment

# strategy:
#   type: Recreate

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.157.0"

ports:
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888

  prometheus:
    enabled: true
    containerPort: 8889
    servicePort: 8889
    protocol: TCP

serviceMonitor:
  enabled: true
  extraLabels:
    release: monitoring
  metricsEndpoints:
  - port: metrics
    interval: 15s
  - port: prometheus
    interval: 15s

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

  connectors:
    servicegraph:
      latency_histogram_buckets:
      - 2ms
      - 8ms
      - 50ms
      - 100ms
      - 200ms
      - 500ms
      - 1s
      - 2s
      - 5s
      - 10s
      dimensions:
      - http.method
      - http.status_code
      store:
        ttl: 60s
        max_items: 1000

  processors:
    batch:
      send_batch_size: 8192
      timeout: 200ms

  exporters:
    otlp/tempo:
      endpoint: tempo.monitoring.svc.cluster.local:4317
      tls:
        insecure: true

    prometheus:
      endpoint: "0.0.0.0:8889"
      metric_expiration: 180s

    debug: {}

  service:
    pipelines:
      traces:
        receivers:
        - otlp
        processors:
        - batch
        exporters:
        - otlp/tempo
        - debug
        - servicegraph

      metrics/servicegraph:
        receivers:
        - servicegraph
        processors:
        - batch
        exporters:
        - prometheus
