apiVersion: apps/v1
kind: Deployment

metadata:
  name: recommendationservice

  labels:
    app: recommendationservice
    component: backend
    service: recommendationservice

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: recommendationservice

  template:
    metadata:
      labels:
        app: recommendationservice
        component: backend
        service: recommendationservice

    spec:
      containers:
        - name: recommendationservice

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

              name: grpc

              protocol: TCP

          env:
            {{- range .Values.containerEnvVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
