replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice
  tag: v0.10.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

containerEnvVars:
  - name: PORT
    value: "8080"

  - name: PRODUCT_CATALOG_SERVICE_ADDR
    value: "productcatalogservice:3550"
